### PR TITLE
Speeding up lookup of inp sections and bracketed words

### PR DESCRIPTION
**Pull request by jackieff**
Addresses #92 by speeding up the search for inp sections and therefore dataframe_from_inp
Changed to search full text file string instead of line iterations

### CODE REVIEW

**Comment by aerispaha** [comment]
@jackieff thanks for this! 

I like your improved logic. That said, I have two comments: 

1. I think this doesn't totally address #92 because with your changes, we still will be scanning the file twice when we call `dataframe_from_inp`. Unless I'm misunderstanding, I think we could merge these changes but keep #92 open. 
2. I wonder if this approach may not be faster when we have very large inp files. Since your method reads the whole text file into memory with `f.read()`, this might lead to a lot of memory usage in some cases. I wonder if we can benchmark this, or maybe you already did some tests that you can share? Or maybe this doesn't matter since most machines have a lot of RAM these days. 

What do you think?

**Comment by jackieff** [comment]
@aerispaha Great points - I'm doing some benchmark tests for #2 right now, and will look more into #1. Stay tuned

**Comment by jackieff** [comment]
@aerispaha Seems that # 2 is not a problem, I tested the [f.read() section](https://github.com/aerispaha/swmmio/pull/117/files#diff-9f3e6f9f1ce68ef682986b5bca636c66be4fd68b7d45bfd14ee40b9b76b7e6caR220-R222) with varying file sizes: 
`File size 557 KB, with 1000 nodes and 1903 links took 0.01 seconds.
File size 5868 KB, with 8749 nodes and 17286 links took 0.07 seconds.
File size 28056 KB, with 43745 nodes and 103715 links took 0.35 seconds.`

**Comment by aerispaha** [comment]
Regarding the performance of this change, another thing we check is the duration of CI unit tests to get an indirect sense of things. Overall, it looks like this makes `swmmio` faster, at least for the test cases. 

version | test job | duration | 🏆 
-------- | ---------| --------- | ---- 
master    | [linux Python 3.8](https://travis-ci.com/github/aerispaha/swmmio/jobs/503222854) | 10.49s | 😢 
31766d6 | [linux Python 3.8](https://travis-ci.com/github/aerispaha/swmmio/jobs/503173476) | 8.25s   | 🏆 
master    | [win Python 3.7](https://ci.appveyor.com/project/aerispaha/swmmio/branch/master#L480) | 16.91s | 😢
31766d6 | [win Python 3.7](https://ci.appveyor.com/project/aerispaha/swmmio/builds/39019900#L481) | 12.64 | 🏆

**Comment by jackieff** [comment]
@aerispaha Newest commit addresses comment # 1. It no longer scans the file twice, because it has a pre-populated `end_strings` list (as you suggested initially), based on `swmmio.defs`

**Review by aerispaha — APPROVED** [review]
looks great

**Pull request merged**
